### require 1 : signup
POST localhost:8080/api/auth/register
Content-Type: application/json

{
  "userId": "yongjin5353",
  "userName": "안용진",
  "userPassword": "12345678aA",
  "userGender": false,
  "userEmail": "yongjin5352@gmail.com"
}

### require 2 : login
POST localhost:8080/api/auth/login
Content-Type: application/json

{
  "userId": "yongjin5353",
  "userPassword": "12345678aA"
}

### test : 출금 계좌 등록
POST localhost:8080/api/accounts
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJ1c2VyUm9sZSI6IkNPTU1PTiIsImV4cCI6MTcyMzc5MzYwNX0.6NI_JPF-u7fRPmZZIAu7iyW704FC8fxqp10E6GrYhR0
Content-Type: application/json

{
  "bank": "대구은행",
  "account": "011-111000-00002"
}