### signup test
POST localhost:8080/api/auth/register
Content-Type: application/json

{
  "userId": "yongjin5351",
  "userName": "안용진",
  "userPassword": "12345678aA",
  "userRole": 0
}

### login test
POST localhost:8080/api/auth/login
Content-Type: application/json

{
  "userId": "yongjin5351",
  "userPassword": "12345678aA"
}
