### signup test
POST localhost:8080/api/auth/register
Content-Type: application/json

{
  "userId": "yongjin5351",
  "userName": "안용진",
  "userPassword": "12345678aA",
  "userRoleEnum": 0
}

### login test
POST localhost:8080/api/auth/login
Content-Type: application/json

{
  "userId": "yongjin5351",
  "userPassword": "12345678aA"
}

### access token refresh
PATCH localhost:8080/api/auth/refresh
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJ1c2VyUm9sZSI6IkFEVkVSVElTRVIiLCJleHAiOjE3MjI0MDQ5MzN9.7ihzVQYqwUQAYM6RfhMyIlqzoLevll-lu4nw2sNGuEg
