### require 1 : signup
POST localhost:8080/api/auth/register
Content-Type: application/json

{
  "userId": "yongjin5353",
  "userName": "안용진",
  "userPassword": "12345678aA",
  "userGender": 0,
  "userEmail": "yongjin5352@gmail.com"
}

### require 2 : login
POST localhost:8080/api/auth/login
Content-Type: application/json

{
  "userId": "yongjin5353",
  "userPassword": "12345678aA"
}

### test : post 등록
POST localhost:8080/api/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJ1c2VyUm9sZSI6IkNPTU1PTiIsImV4cCI6MTcyMzE3NTk3N30.Bylxz7B356rFpiz_ZK3rnXd4fkPI7FkNEedXI-VX8tI
Content-Type: application/json

{
  "title": "공고11",
  "content": "공고입니다.",
  "price": 3000000,
  "extraPrice": 20000,
  "endDate": "2024-09-05"
}

### test : 공고 전체 조회
GET localhost:8080/api/posts

### test : 공고 개별 조회
GET localhost:8080/api/posts/1

### test : 공고 수정
PUT localhost:8080/api/posts/1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJ1c2VyUm9sZSI6IkNPTU1PTiIsImV4cCI6MTcyMzE3NTk3N30.Bylxz7B356rFpiz_ZK3rnXd4fkPI7FkNEedXI-VX8tI
Content-Type: application/json

{
  "title": "공고11",
  "content": "공고입니닷",
  "price": 3000000,
  "extraPrice": 20000,
  "endDate": "2024-09-05"
}

### test : 공고 삭제
DELETE localhost:8080/api/posts/1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJ1c2VyUm9sZSI6IkNPTU1PTiIsImV4cCI6MTcyMjg1NTQ3Nn0.020kZQ86UOTGhUwP-yheYY44gasbAEqhIShPYAAxeHU