### require 1 : signup
POST localhost:8080/api/auth/register
Content-Type: application/json

{
  "userId": "yongjin5353",
  "userName": "안용진",
  "userPassword": "12345678aA",
  "userGender": 0,
  "userEmail": "yongjin5352@gmail.com"
}

### require 2 : login
POST localhost:8080/api/auth/login
Content-Type: application/json

{
  "userId": "yongjin5353",
  "userPassword": "12345678aA"
}

### test : post 등록
POST localhost:8080/api/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJ1c2VyUm9sZSI6IkNPTU1PTiIsImV4cCI6MTcyMjU4MTk1NX0.RPVU6gTgcaF-8p75NQEZX4fNXKRk6XA3qsENMz8m1yY
Content-Type: application/json

{
  "title": "공고11",
  "content": "공고입니다.",
  "price": 3000000,
  "extraPrice": 20000,
  "endDate": "2024-03-05T12:12:12.000Z"
}